### ISSUE TITLE
Makes no sense as an else if

### ISSUE THREAD

**Issue by mayisa87** [asharif123/numbers_guessing#1]
https://github.com/asharif123/numbers_guessing/blob/1b5e62b6cccd21f15d63b71ec5c7bdc80df398fe/Program.cs#L42-L46

As this is the exceptional case, you should do it in a separated if before all other stuff, directly after reading the input from user. It should not be part of the if/else chain at all.

**Comment by asharif123** [comment]
fixed issue #1 getting rid of unnecessary else if statement
