### ISSUE TITLE
Don't do calculations directly in your if statement

### ISSUE THREAD

**Issue by mayisa87** [asharif123/numbers_guessing#10]
I really like the way you implemente the offset bonus stage! Great that you used Math.Abs here!

If you have something like this statement, avoid to have calculations in your condition directly, as they get hard to read. Especially as you use the same calculation and same method Math.Abs on two places. Better store the result of the Math.Abs to a variable.

And make the 5 a constant.

else if (userGuess < randomNumber && (Math.Abs(randomNumber - userGuess) <= 5))

**Comment by asharif123** [comment]
fixed issue #10 by not performing calculations directly in if statements
