### ISSUE TITLE
Put more love into this block :)

### ISSUE THREAD

**Issue by mayisa87** [asharif123/numbers_guessing#11]
![image](https://github.com/asharif123/numbers_guessing/assets/130921606/1c511e13-681c-4051-bf5f-0058f0a1ea86)

and this block definitely needs a it more love

You have some duplicated code (the "You have .. guesses left" for example)
and could refactor this block a little bit to make it less redundant:
for example you could build a string with all the information to show:
1. check if guess was to high or to low
2. append the "you are close" block when the guess was within range
3. append guesses left
4. print the build string

**Comment by asharif123** [comment]
fixed issue #11 by optimizing if statement checking user's guess
