### ISSUE TITLE
Break in case of for loop?

### ISSUE THREAD

**Issue by mayisa87** [asharif123/numbers_guessing#3]
https://github.com/asharif123/numbers_guessing/blob/1b5e62b6cccd21f15d63b71ec5c7bdc80df398fe/Program.cs#L31

A for loop has the characteristic that it will end after a certain amount of iterations, by definition.
So it makes not much sense to check inside of the loop if the counter has reached last iteration, and then break.

SO if you have a loop like
for (int i=0; **i<4**; i++)

it will loop 0 , 1 ,2 , 3 and at the next try, it won't enter loop again, as 4 would not match the condition, so you don't need to do a break therefore at all.

**Comment by asharif123** [comment]
Fixed issue #3 by getting rid of unnecessary break statement in if statement
