### ISSUE TITLE
& operator is not the same as &&

### ISSUE THREAD

**Issue by mayisa87** [asharif123/numbers_guessing#4]
https://github.com/asharif123/numbers_guessing/blob/1b5e62b6cccd21f15d63b71ec5c7bdc80df398fe/Program.cs#L31

Take care when using logical operators. & is not &&

& is a bit operator, which is used to logically check on the bits of a number for example. So you may know, that each number in background is build out of 0 and 1, so called bits, and you can work with them too, and therefore there are operators that can be used for this "Bitwise operations"

&& is what you want to use if you want to compare values like numbers strings or whatever.

**Comment by asharif123** [comment]
fixed issue #4 by replacing & with &&
