### ISSUE TITLE
Random.NExt does not include upper bound

### ISSUE THREAD

**Issue by mayisa87** [asharif123/numbers_guessing#5]
https://github.com/asharif123/numbers_guessing/blob/1b5e62b6cccd21f15d63b71ec5c7bdc80df398fe/Program.cs#L22

Have a look to the documentation of the Random method Next

[[If you have](https://learn.microsoft.com/en-us/dotnet/api/system.random.next?view=net-7.0)](https://learn.microsoft.com/en-us/dotnet/api/system.random.next?view=net-7.0#system-random-next(system-int32-system-int32))

It does not include the upper bound, so if you use 1 and 100 it will give you a number between 1 and 99

**Comment by asharif123** [comment]
fixed issue #5 to include upper bound to go up to 100
