### ISSUE TITLE
Check for last round

### ISSUE THREAD

**Issue by mayisa87** [asharif123/numbers_guessing#7]
https://github.com/asharif123/numbers_guessing/blob/34a418b24b649d54843ef9e5744d9745bcd56642/Program.cs#L24-L27

The user enters the last time a number to guess. If it is not OK you output GAME OVER, and then anyway go further and output "too low" etc. 
This is not a good way to do so, because the Game Over should be something that is output to user at the very last point.

So a better way would be, to only check if the guesses left is already 0 and do this at the very end of the loop, or even outside of the loop.
The loop will stop anyway, so if you recognize outside of the loop that the max guesses was reached and last entered number is not ok, you know, user did not guess right. Benefit: The if is not executed in each iteration, as it is only needed in case of last trial.

**Comment by asharif123** [comment]
fixed issue #7 by adding game over if statement code to the end of the program

**Comment by incredibleLeitman** [comment]
As @mayisa87 mentioned this can be improved by moving the check outside of the loop -> this way your program does not have to check the condition for each iteration but only after the loop ends

**Comment by mayisa87** [comment]
As Micheal wrote, because it wouldn't be executed each iteration of the loop, but only once after the loop. It is always better to place code on a position, where it is exectued as less as possible. INside of your loop it is executed several times, for nothing, as it will anyway only match in case of last iteration. 

And you should have learned by now, that you can declare variables at a certain point, and use it then in different places. So if you define the userGuess before the loop, use it inside the loop, you will have the last entered value also available outside the loop.

**Comment by asharif123** [comment]
fixed issue #7 by moving game over code to the very end of the program after for loop
