### ISSUE TITLE
Check at very first!

### ISSUE THREAD

**Issue by mayisa87** [asharif123/numbers_guessing#8]
https://github.com/asharif123/numbers_guessing/blob/34a418b24b649d54843ef9e5744d9745bcd56642/Program.cs#L34-L38

Take care of the sequence you are doing things and writing code. If you want to validate an input, do this directly after reading the input. Not after arleady checking the value of it and outputing some messages to user. And instead of using "return" which will close the whole application, you could rewatch this video (https://course.raketementoring.com/courses/rakete-mentoring/lectures/45560188) There is another key word beside break you can use ;)

**Comment by asharif123** [comment]
fixed issue #8 by fixing sequencing of if statements
