### ISSUE TITLE
This is not an else at all

### ISSUE THREAD

**Issue by mayisa87** [asharif123/numbers_guessing#9]
https://github.com/asharif123/numbers_guessing/blob/34a418b24b649d54843ef9e5744d9745bcd56642/Program.cs#L42

YOu first do some general if statements checkin if the input was valid, if you reached last round or alraedy have a match.

If all of this is not the case, then you start checking on the value. So this is again a separated if and should not start with else at all.

**Comment by asharif123** [comment]
fixed issue #9 by getting rid of unnecessary else statement
